#!/bin/sh

#
# This script will generate coverage into a coverage directory.
#
# Run:
#
# npm install istanbul
# t/cover && open coverage/lcov-report/index.html
#
# It is not difficult to keep coverage at 100%.
#

set -e

rm -rf coverage

count=1;
for file in $(find t -name \*.t.js); do
  node_modules/.bin/istanbul cover -x 't/**' $file > /dev/null 2>&1
  mv coverage/coverage.json coverage/coverage$count.json
  count=$(expr $count + 1)
done

node_modules/.bin/istanbul report --root coverage --dir coverage > /dev/null

sed -i -e s,'^SF:'`pwd`/,SF:, coverage/lcov.info

exit 0
